ERROR | 2021-12-02 15:20:12 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:12 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:13 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:13 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:14 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:14 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:15 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:15 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:16 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:16 | [main] processor.Processor_001 (Processor_001.java:67) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in file [D:\TONG\JAVA\ta-mock-proj\target\classes\mapper\AccountApplicationDao.xml]
### The error may involve com.psbc.mapper.AccountApplicationDao.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
ERROR | 2021-12-02 15:20:31 | [main] service.SucceedRecordOperator (SucceedRecordOperator.java:78) - java.lang.NullPointerException
INFO  | 2021-12-02 15:20:31 | [main] processor.Processor_001 (Processor_001.java:167) - [AccountConfirmation(confirmid=1, transactioncfmdate=20211202, returncode=0000, businesscode=101, transactiondate=20211101, transactiontime=100012, taserialno=2021120215203165435, fromtaflag=0, regioncode=0001, netno=10, specification=, customerno=null, errordetail=null, taaccountid=012208963, appsheetserialno=211101FSM0r0220204), AccountConfirmation(confirmid=2, transactioncfmdate=20211202, returncode=0000, businesscode=101, transactiondate=20211101, transactiontime=144536, taserialno=20211202152031676667, fromtaflag=0, regioncode=0001, netno=10, specification=, customerno=null, errordetail=null, taaccountid=060729769, appsheetserialno=211029FSM0r0120104), AccountConfirmation(confirmid=3, transactioncfmdate=20211202, returncode=0000, businesscode=101, transactiondate=20211101, transactiontime=100852, taserialno=20211202152031701116, fromtaflag=0, regioncode=0001, netno=10, specification=, customerno=null, errordetail=null, taaccountid=093216517, appsheetserialno=211030FSM0r0120201), AccountConfirmation(confirmid=4, transactioncfmdate=20211202, returncode=0000, businesscode=101, transactiondate=20211101, transactiontime=143944, taserialno=20211202152031718831, fromtaflag=0, regioncode=0001, netno=10, specification=, customerno=null, errordetail=null, taaccountid=013981130, appsheetserialno=211101FSM0r0120501), AccountConfirmation(confirmid=5, transactioncfmdate=20211202, returncode=0000, businesscode=101, transactiondate=20211101, transactiontime=144552, taserialno=20211202152031734988, fromtaflag=0, regioncode=0001, netno=10, specification=, customerno=null, errordetail=null, taaccountid=022988876, appsheetserialno=211101FSM0r0120502)]
INFO  | 2021-12-02 15:20:31 | [main] psbc.TaMockProjectApplication (TaMockProjectApplication.java:38) - process 001 done!
